### ISSUE TITLE
"Failed updating permissions on script file" Error on update-bitwarden.ps1

### ISSUE THREAD

**Issue by dohlin** [ZacksHomeLab/BitWarden#1]
Let me start out this issue by noting that it's entirely possible I've got something else going on as I've had a selfhosted BW instance for years now so am sorta "side stepping" into this.  My primary backups have been and continue to be Veeam based but I am interested in the auto-backup and auto-upgrade scripts.  I successfully got the auto-backup script working but am running into the following error when I run the auto-upgrade script:

```
~$ sudo /usr/bin/pwsh -File "/opt/bitwarden/update-bitwarden.ps1" -PasswordFile /opt/bitwarden/password_file -FinalBackupLocation /backups -LogFile /opt/bitwarden/update-bitwarden.log
Main: Checking preconditions before we start...
Main: Current Core ID: bitwarden/admin:2022.12.0:
Main: Current Web ID: bitwarden/web:2022.12.0:
Main: Downloading latest bitwarden script...
Main: Updating permissions on bitwarden script file /opt/bitwarden-2022-12-28-09-21/bitwarden.sh...                     
WARNING: Main: Failed updating permissions on script file /opt/bitwarden-2022-12-28-09-21/bitwarden.sh.
```

First glance this seemed to me like a possible permissions issue, but even running as root (sudo su and then run again) I get the same error.  I should also note that I got the error while still on v2022.10.0 before just saying screw it and manually upgrading to v2022.12.0.  I feel like I might be missing something obvious here, but can't figure out what.  Any ideas?  Thank you for this awesome contribution to the community!

**Comment by ZacksHomeLab** [comment]
Hi! I believe I might know what the issue is. In the setup documentation, there was a step I omitted but forgot to update the script to reflect said change. 

The issue is within `function Update-BitWardenPermissions`. In the begin section, there's a variable with the incorrect group, which will need to be updated:
`$CORRECT_GROUP_PERMISSIONS = "bitwarden"`
to
`$CORRECT_GROUP_PERMISSIONS = "docker"`

I will update the script to fix this issue. Thanks a bunch for bringing this to light!
